<a href="https://colab.research.google.com/github/leeandrei/Numerical-Methods-/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

##Determinants of Matrix using numpy.linalg.det



In [16]:
A = np.array([[1, 2, -1], [4, 6, -2], [-1, 3, 3]])
B = int(np.linalg.det(A))

print(A)
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-14
