<a href="https://colab.research.google.com/github/leeandrei/Numerical-Methods-/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix And It's Operation

##$$A = \begin{bmatrix} -5 & 0 \\4 & 1 \\\end{bmatrix} , B = \begin{bmatrix} 6 & -3\\2 & 3\\\end{bmatrix} $$##

In [1]:
import numpy as np 

#####1. sum = A + B 

In [8]:
A = np.array([[-5, 0], [4, 1]])
B = np.array([[6, -3], [2, 3]])

sum = A + B
print(sum)

[[ 1 -3]
 [ 6  4]]


#####2. difference1 = B - A


In [7]:
difference1 = B -A 

print(difference1)

[[11 -3]
 [-2  2]]


#####3. difference2 = A - B 

In [9]:
difference2 = A - B

print(difference2)

[[-11   3]
 [  2  -2]]
